name = "lavendar"
main = "src/worker/index.ts"
compatibility_date = "2025-01-01"

[observability]
enabled = true

[assets]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "lavendar-db"
database_id = "27b67368-fbfc-4b55-bbf6-d7fca8918263"
