name = "lavender"
main = "src/worker/index.ts"
compatibility_date = "2025-01-01"

[observability]
enabled = true

[assets]
not_found_handling = "single-page-application"


[[d1_databases]]
binding = "lavender_db"
database_name = "lavender-db"
database_id = "bbc77a7e-325b-4426-8e96-7fffe2941ea7"
